/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.ShowDialog;
import java.awt.Color;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author chicu
 */
public class FrmMain extends javax.swing.JFrame {

    //dùng để lưu lại danh sách các tab dang mở
    private ArrayList<DataTab> btn = new ArrayList();
    //icon close tab khi chưa rê chuột vào
    private final ImageIcon icon = new ImageIcon(getClass().getResource("Images/close.png"));
    //icon close tab khi rê chuột vào
    private final ImageIcon iconhover = new ImageIcon(getClass().getResource("Images/close_hover.png"));

    /**
     * Creates new form Main
     */
    //tạo đối tượng lưu trữ các tab
    public class DataTab {

        private JButton btn;
        private int id;

        public DataTab() {
            this.btn = new JButton();
            id = 0;
        }

        public DataTab(JButton btn, int id) {
            this.btn = btn;
            this.id = id;
        }

        public JButton getBtn() {
            return this.btn;
        }

        public int getId() {
            return this.id;
        }
    }

    public FrmMain() {
        initComponents();
        //Mở full màn hình khi chạy phần mềm
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
        setTitle("Quản lý nhân sự");
        //tạo size bằng kích thước màn hình
        setSize(getMaximumSize());
        createTab("Trang Chủ", new FrmHome(), 0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        importExportTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel(){    
            public void paintComponent(Graphics g){     
                ImageIcon icon=new ImageIcon(getClass().getResource("/GUI/Images/bg2.png"));     
                g.drawImage(icon.getImage(),0 , 0, jPanel1.getWidth(), jPanel1.getHeight(), null);       
                setOpaque(false);     
                super.paintComponent(g);     
            } 
        };
        jPanel12 = new javax.swing.JPanel(){    
            public void paintComponent(Graphics g){     
                ImageIcon icon=new ImageIcon(getClass().getResource("/GUI/Images/bg2.png"));     
                g.drawImage(icon.getImage(),0 , 0, jPanel12.getWidth(), jPanel12.getHeight(), null);       
                setOpaque(false);     
                super.paintComponent(g);     
            } 
        };
        employeeLabel = new javax.swing.JLabel();
        departmentLabel1 = new javax.swing.JLabel();
        salaryLabel = new javax.swing.JLabel();
        studyLabel = new javax.swing.JLabel();
        rankLabel = new javax.swing.JLabel();
        awardAndPunishmentLabel = new javax.swing.JLabel();
        thongkeLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel(){    
            public void paintComponent(Graphics g){     
                ImageIcon icon=new ImageIcon(getClass().getResource("/GUI/Images/bg2.png"));     
                g.drawImage(icon.getImage(),0 , 0, jPanel2.getWidth(), jPanel2.getHeight(), null);       
                setOpaque(false);     
                super.paintComponent(g);     
            } 
        };
        jPanel4 = new javax.swing.JPanel(){    
            public void paintComponent(Graphics g){     
                ImageIcon icon=new ImageIcon(getClass().getResource("/GUI/Images/bg2.png"));     
                g.drawImage(icon.getImage(),0 , 0, jPanel4.getWidth(), jPanel4.getHeight(), null);       
                setOpaque(false);     
                super.paintComponent(g);     
            } 
        };
        salaryExportPanel = new javax.swing.JPanel(){    
            public void paintComponent(Graphics g){     
                ImageIcon icon=new ImageIcon(getClass().getResource("/GUI/Images/bg2.png"));     
                g.drawImage(icon.getImage(),0 , 0, salaryExportPanel.getWidth(), salaryExportPanel.getHeight(), null);       
                setOpaque(false);     
                super.paintComponent(g);     
            } 
        };
        salaryExportLabel = new javax.swing.JLabel();
        employeeExportPanel = new javax.swing.JPanel(){    
            public void paintComponent(Graphics g){     
                ImageIcon icon=new ImageIcon(getClass().getResource("/GUI/Images/bg2.png"));     
                g.drawImage(icon.getImage(),0 , 0, employeeExportPanel.getWidth(), employeeExportPanel.getHeight(), null);       
                setOpaque(false);     
                super.paintComponent(g);     
            } 
        };
        employeeExportLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel(){    
            public void paintComponent(Graphics g){     
                ImageIcon icon=new ImageIcon(getClass().getResource("/GUI/Images/bg2.png"));     
                g.drawImage(icon.getImage(),0 , 0, jPanel5.getWidth(), jPanel5.getHeight(), null);       
                setOpaque(false);     
                super.paintComponent(g);     
            } 
        };
        employeeImportPanel = new javax.swing.JPanel(){    
            public void paintComponent(Graphics g){     
                ImageIcon icon=new ImageIcon(getClass().getResource("/GUI/Images/bg2.png"));     
                g.drawImage(icon.getImage(),0 , 0, employeeImportLabel.getWidth(), employeeImportLabel.getHeight(), null);       
                setOpaque(false);     
                super.paintComponent(g);     
            } 
        };
        employeeImportLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel(){    
            public void paintComponent(Graphics g){     
                ImageIcon icon=new ImageIcon(getClass().getResource("/GUI/Images/bg2.png"));     
                g.drawImage(icon.getImage(),0 , 0, jPanel3.getWidth(), jPanel3.getHeight(), null);       
                setOpaque(false);     
                super.paintComponent(g);     
            } 
        };
        jPanel9 = new javax.swing.JPanel(){    
            public void paintComponent(Graphics g){     
                ImageIcon icon=new ImageIcon(getClass().getResource("/GUI/Images/bg2.png"));     
                g.drawImage(icon.getImage(),0 , 0, jPanel9.getWidth(), jPanel9.getHeight(), null);       
                setOpaque(false);     
                super.paintComponent(g);     
            } 
        };
        softwareInfoPanel = new javax.swing.JPanel(){    
            public void paintComponent(Graphics g){     
                ImageIcon icon=new ImageIcon(getClass().getResource("/GUI/Images/bg2.png"));     
                g.drawImage(icon.getImage(),0 , 0, softwareInfoPanel.getWidth(), softwareInfoPanel.getHeight(), null);       
                setOpaque(false);     
                super.paintComponent(g);     
            } 
        };
        softwareInfoLabel = new javax.swing.JLabel();
        phonePanel = new javax.swing.JPanel(){    
            public void paintComponent(Graphics g){     
                ImageIcon icon=new ImageIcon(getClass().getResource("/GUI/Images/bg2.png"));     
                g.drawImage(icon.getImage(),0 , 0, phonePanel.getWidth(), phonePanel.getHeight(), null);       
                setOpaque(false);     
                super.paintComponent(g);     
            } 
        };
        phoneLabel = new javax.swing.JLabel();
        tabmain = new javax.swing.JTabbedPane();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(970, 500));

        importExportTab.setPreferredSize(new java.awt.Dimension(970, 141));

        employeeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/pupils.png"))); // NOI18N
        employeeLabel.setText("<html><center>Danh sách <br>nhân viên</center></html>");
        employeeLabel.setToolTipText("");
        employeeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employeeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                employeeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                employeeLabelMouseExited(evt);
            }
        });

        departmentLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        departmentLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/phongban.png"))); // NOI18N
        departmentLabel1.setText("<html></center>Phòng ban</center></html>");
        departmentLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        departmentLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                departmentLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                departmentLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                departmentLabel1MouseExited(evt);
            }
        });

        salaryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salaryLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/bangluong.png"))); // NOI18N
        salaryLabel.setText("<html>Bảng lương</html>");
        salaryLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salaryLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salaryLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salaryLabelMouseExited(evt);
            }
        });

        studyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studyLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/hocvan.png"))); // NOI18N
        studyLabel.setText("<html>Học vấn</html>");
        studyLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studyLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studyLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studyLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studyLabelMouseExited(evt);
            }
        });

        rankLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rankLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/chuyenmon.png"))); // NOI18N
        rankLabel.setText("<html>Chức vụ</html>");
        rankLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rankLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rankLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rankLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rankLabelMouseExited(evt);
            }
        });

        awardAndPunishmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        awardAndPunishmentLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/khenthuongkyluat.png"))); // NOI18N
        awardAndPunishmentLabel.setText("<html>Khen thưởng<br> kỷ luật</html>");
        awardAndPunishmentLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        awardAndPunishmentLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                awardAndPunishmentLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                awardAndPunishmentLabelMouseExited(evt);
            }
        });

        thongkeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thongkeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/thongke.png"))); // NOI18N
        thongkeLabel.setText("<html><center>Thống kê</center></html>");
        thongkeLabel.setToolTipText("");
        thongkeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        thongkeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thongkeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                thongkeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                thongkeLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(employeeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(departmentLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(salaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(studyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(rankLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(awardAndPunishmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(thongkeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(departmentLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(salaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(rankLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studyLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(thongkeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(awardAndPunishmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        importExportTab.addTab("Quản lý", jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Xuất dữ liệu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        salaryExportLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salaryExportLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/export1.png"))); // NOI18N
        salaryExportLabel.setText("<html><center>Xuất bảng<br> lương</center></html>");
        salaryExportLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salaryExportLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salaryExportLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salaryExportLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salaryExportLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout salaryExportPanelLayout = new javax.swing.GroupLayout(salaryExportPanel);
        salaryExportPanel.setLayout(salaryExportPanelLayout);
        salaryExportPanelLayout.setHorizontalGroup(
            salaryExportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salaryExportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        salaryExportPanelLayout.setVerticalGroup(
            salaryExportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salaryExportLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );

        employeeExportLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeExportLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/export.png"))); // NOI18N
        employeeExportLabel.setText("<html><center>Xuất DS<br> nhân viên</center></html>");
        employeeExportLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employeeExportLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeExportLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                employeeExportLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                employeeExportLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout employeeExportPanelLayout = new javax.swing.GroupLayout(employeeExportPanel);
        employeeExportPanel.setLayout(employeeExportPanelLayout);
        employeeExportPanelLayout.setHorizontalGroup(
            employeeExportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeExportPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(employeeExportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        employeeExportPanelLayout.setVerticalGroup(
            employeeExportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(employeeExportLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salaryExportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(employeeExportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(salaryExportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(employeeExportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập dữ liệu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        employeeImportPanel.setPreferredSize(new java.awt.Dimension(100, 54));

        employeeImportLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        employeeImportLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/import.png"))); // NOI18N
        employeeImportLabel.setText("<html><center>Nhập DS nhân viên</center></html>");
        employeeImportLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employeeImportLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeImportLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                employeeImportLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                employeeImportLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout employeeImportPanelLayout = new javax.swing.GroupLayout(employeeImportPanel);
        employeeImportPanel.setLayout(employeeImportPanelLayout);
        employeeImportPanelLayout.setHorizontalGroup(
            employeeImportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(employeeImportLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
        );
        employeeImportPanelLayout.setVerticalGroup(
            employeeImportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeImportPanelLayout.createSequentialGroup()
                .addComponent(employeeImportLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(employeeImportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(employeeImportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 462, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        importExportTab.addTab("Nhập/Xuất dữ liệu", jPanel2);

        softwareInfoPanel.setPreferredSize(new java.awt.Dimension(120, 74));

        softwareInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        softwareInfoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/thongtinphanmem.png"))); // NOI18N
        softwareInfoLabel.setText("<html><center>Thông Tin<br>Phần Mềm</center></html>");
        softwareInfoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        softwareInfoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                softwareInfoLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                softwareInfoLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                softwareInfoLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout softwareInfoPanelLayout = new javax.swing.GroupLayout(softwareInfoPanel);
        softwareInfoPanel.setLayout(softwareInfoPanelLayout);
        softwareInfoPanelLayout.setHorizontalGroup(
            softwareInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(softwareInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        softwareInfoPanelLayout.setVerticalGroup(
            softwareInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(softwareInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
        );

        phonePanel.setPreferredSize(new java.awt.Dimension(120, 74));

        phoneLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phoneLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/phone.png"))); // NOI18N
        phoneLabel.setText("Liên lạc");
        phoneLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        phoneLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoneLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                phoneLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                phoneLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout phonePanelLayout = new javax.swing.GroupLayout(phonePanel);
        phonePanel.setLayout(phonePanelLayout);
        phonePanelLayout.setHorizontalGroup(
            phonePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(phoneLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        phonePanelLayout.setVerticalGroup(
            phonePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(phoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(softwareInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(phonePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(phonePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(softwareInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(702, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        importExportTab.addTab("Hỗ trợ", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(importExportTab, javax.swing.GroupLayout.PREFERRED_SIZE, 984, Short.MAX_VALUE)
                    .addComponent(tabmain)
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(importExportTab, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(tabmain, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseTab(ActionEvent e) {
        //duyệt tất cả các tab đang mở
        for (int i = 0; i < btn.size(); i++) {
            //tìm tab vừa click vào. Nếu tìm thấy thì xóa tab đó khỏi tabmain
            if (e.getSource() == btn.get(i).getBtn()) {
                tabmain.remove(i);
                btn.remove(i);
                break;
            }
        }
    }
    //Đóng 1 tab

    public void CloseTab(int index) {
        tabmain.remove(index);
        btn.remove(index);
    }

    //sự kiện hover button close
    private void HoverButton(java.awt.event.MouseEvent evt, ImageIcon iin) {
        for (int i = 0; i < btn.size(); i++) {
            if (evt.getSource() == btn.get(i).getBtn()) {
                btn.get(i).getBtn().setIcon(iin);
                break;
            }
        }
    }

    public void createTab(String title, Component cpt, int id) {
        //add 1 tab vào jTabbedPane
        tabmain.addTab("", cpt);
        FlowLayout f = new FlowLayout(FlowLayout.CENTER, 5, 0);
        JPanel pnlTab = new JPanel(f);
        pnlTab.setOpaque(false);
        //tiêu đề tab
        JLabel lb = new JLabel(title);

        //button close
        JButton closeTab = new JButton();
        closeTab.setIcon(icon);
        closeTab.setToolTipText("Close Tab");
        closeTab.setOpaque(false);
        closeTab.setBorder(null);
        /*Set button trong suốt*/
        closeTab.setContentAreaFilled(false);
        closeTab.setFocusPainted(false);
        closeTab.setFocusable(false);

        pnlTab.add(lb);
        pnlTab.add(closeTab);
        btn.add(new DataTab(closeTab, id));
        tabmain.setTabComponentAt(tabmain.getTabCount() - 1, pnlTab);
        tabmain.setSelectedIndex(tabmain.getTabCount() - 1);

        //Sư kiện close tab
        closeTab.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CloseTab(e);
            }
        });

        //Sự kiện hover
        closeTab.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HoverButton(evt, iconhover);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HoverButton(evt, icon);
            }
        });
    }

    private boolean KiemTraTab(int id) {
        for (int i = 0; i < btn.size(); i++) {
            if (btn.get(i).getId() == id) {
                //nếu đã được mở thì select vào tab đó
                tabmain.setSelectedIndex(i);
                return false;
            }
        }
        return true;
    }

    private void awardAndPunishmentLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_awardAndPunishmentLabelMouseExited
        // TODO add your handling code here:
        awardAndPunishmentLabel.setBorder(null);
    }//GEN-LAST:event_awardAndPunishmentLabelMouseExited

    private void awardAndPunishmentLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_awardAndPunishmentLabelMouseEntered
        // TODO add your handling code here:
        awardAndPunishmentLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));
    }//GEN-LAST:event_awardAndPunishmentLabelMouseEntered

    private void rankLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rankLabelMouseExited
        // TODO add your handling code here:
        rankLabel.setBorder(null);
    }//GEN-LAST:event_rankLabelMouseExited

    private void rankLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rankLabelMouseEntered
        // TODO add your handling code here:
        rankLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));
    }//GEN-LAST:event_rankLabelMouseEntered

    private void studyLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studyLabelMouseExited
        // TODO add your handling code here:
        studyLabel.setBorder(null);
    }//GEN-LAST:event_studyLabelMouseExited

    private void studyLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studyLabelMouseEntered
        // TODO add your handling code here:
        studyLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));
    }//GEN-LAST:event_studyLabelMouseEntered

    private void salaryLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salaryLabelMouseExited
        // TODO add your handling code here:
        salaryLabel.setBorder(null);
    }//GEN-LAST:event_salaryLabelMouseExited

    private void salaryLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salaryLabelMouseEntered
        // TODO add your handling code here:
        salaryLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));
    }//GEN-LAST:event_salaryLabelMouseEntered

    private void departmentLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departmentLabel1MouseExited
        // TODO add your handling code here:
        departmentLabel1.setBorder(null);
    }//GEN-LAST:event_departmentLabel1MouseExited

    private void departmentLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departmentLabel1MouseEntered
        // TODO add your handling code here:
        departmentLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));
    }//GEN-LAST:event_departmentLabel1MouseEntered

    private void softwareInfoLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_softwareInfoLabelMouseEntered
        // TODO add your handling code here:
        softwareInfoLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));
    }//GEN-LAST:event_softwareInfoLabelMouseEntered

    private void softwareInfoLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_softwareInfoLabelMouseExited
        // TODO add your handling code here:
        softwareInfoLabel.setBorder(null);
    }//GEN-LAST:event_softwareInfoLabelMouseExited

    private void phoneLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneLabelMouseEntered
        // TODO add your handling code here:
        phoneLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));

    }//GEN-LAST:event_phoneLabelMouseEntered

    private void phoneLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneLabelMouseExited
        // TODO add your handling code here:
        phoneLabel.setBorder(null);

    }//GEN-LAST:event_phoneLabelMouseExited

    private void salaryExportLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salaryExportLabelMouseEntered
        // TODO add your handling code here:
        salaryExportLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));
    }//GEN-LAST:event_salaryExportLabelMouseEntered

    private void salaryExportLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salaryExportLabelMouseExited
        // TODO add your handling code here:
        salaryExportLabel.setBorder(null);
    }//GEN-LAST:event_salaryExportLabelMouseExited

    private void employeeExportLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeExportLabelMouseEntered
        // TODO add your handling code here:
        employeeExportLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));
    }//GEN-LAST:event_employeeExportLabelMouseEntered

    private void employeeExportLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeExportLabelMouseExited
        // TODO add your handling code here:
        employeeExportLabel.setBorder(null);
    }//GEN-LAST:event_employeeExportLabelMouseExited

    private void employeeImportLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeImportLabelMouseEntered
        // TODO add your handling code here:
        employeeImportLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));
    }//GEN-LAST:event_employeeImportLabelMouseEntered

    private void employeeImportLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeImportLabelMouseExited
        // TODO add your handling code here:
        employeeImportLabel.setBorder(null);
    }//GEN-LAST:event_employeeImportLabelMouseExited

    private void departmentLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departmentLabel1MouseClicked
        // TODO add your handling code here:
        if (KiemTraTab(2)) {
            createTab("Phòng Ban", new FrmPhongBan(), 2);
        }
    }//GEN-LAST:event_departmentLabel1MouseClicked

    private void employeeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeLabelMouseExited
        // TODO add your handling code here:
        employeeLabel.setBorder(null);
    }//GEN-LAST:event_employeeLabelMouseExited

    private void employeeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeLabelMouseEntered
        // TODO add your handling code here:
        employeeLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));
    }//GEN-LAST:event_employeeLabelMouseEntered

    private void employeeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeLabelMouseClicked
        // TODO add your handling code here:
        if (KiemTraTab(1)) {
            createTab("Danh sách nhân viên", new FrmDSNV(), 1);
        }
    }//GEN-LAST:event_employeeLabelMouseClicked

    private void rankLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rankLabelMouseClicked
        // TODO add your handling code here:
        if (KiemTraTab(5)) {
            createTab("Chức vụ", new FrmChucVu(), 5);
        }
    }//GEN-LAST:event_rankLabelMouseClicked

    private void studyLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studyLabelMouseClicked
        // TODO add your handling code here:
        if (KiemTraTab(4)) {
            createTab("Học vấn", new FrmTDHV(), 4);
        }
    }//GEN-LAST:event_studyLabelMouseClicked

    private void employeeExportLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeExportLabelMouseClicked
        // TODO add your handling code here:
        if (KiemTraTab(9)) {
            createTab("Xuất danh sách nhân viên", new FrmXuatDSNV(), 9);
        }
    }//GEN-LAST:event_employeeExportLabelMouseClicked

    private void employeeImportLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeImportLabelMouseClicked
        // TODO add your handling code here:
        if (KiemTraTab(10)) {
            createTab("Nhập danh sách nhân viên", new FrmNhapDSNV(), 10);
        }
    }//GEN-LAST:event_employeeImportLabelMouseClicked

    private void salaryExportLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salaryExportLabelMouseClicked
        // TODO add your handling code here:
        if (KiemTraTab(8)) {
            createTab("Xuất bảng lương", new FrmXuatBangLuong(), 8);
        }
    }//GEN-LAST:event_salaryExportLabelMouseClicked

    private void softwareInfoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_softwareInfoLabelMouseClicked
        // TODO add your handling code here:
        new ShowDialog(this).Show("Thông in phần mềm", new FrmTTPM(), 410, 250);
    }//GEN-LAST:event_softwareInfoLabelMouseClicked

    private void phoneLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneLabelMouseClicked
        // TODO add your handling code here:
        new ShowDialog(this).Show("Thông tin liên hệ", new FrmLienHe(), 410, 335);
    }//GEN-LAST:event_phoneLabelMouseClicked

    private void thongkeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongkeLabelMouseEntered
        // TODO add your handling code here:
        thongkeLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));
    }//GEN-LAST:event_thongkeLabelMouseEntered

    private void thongkeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongkeLabelMouseExited
        // TODO add your handling code here:
        thongkeLabel.setBorder(null);
    }//GEN-LAST:event_thongkeLabelMouseExited

    private void thongkeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongkeLabelMouseClicked
        // TODO add your handling code here:
        if (KiemTraTab(7)) {
            createTab("Thống kê", new FrmThongKe(), 7);
        }
    }//GEN-LAST:event_thongkeLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel awardAndPunishmentLabel;
    private javax.swing.JLabel departmentLabel1;
    private javax.swing.JLabel employeeExportLabel;
    private javax.swing.JPanel employeeExportPanel;
    private javax.swing.JLabel employeeImportLabel;
    private javax.swing.JPanel employeeImportPanel;
    private javax.swing.JLabel employeeLabel;
    private javax.swing.JTabbedPane importExportTab;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JPanel phonePanel;
    private javax.swing.JLabel rankLabel;
    private javax.swing.JLabel salaryExportLabel;
    private javax.swing.JPanel salaryExportPanel;
    private javax.swing.JLabel salaryLabel;
    private javax.swing.JLabel softwareInfoLabel;
    private javax.swing.JPanel softwareInfoPanel;
    private javax.swing.JLabel studyLabel;
    private javax.swing.JTabbedPane tabmain;
    private javax.swing.JLabel thongkeLabel;
    // End of variables declaration//GEN-END:variables
}
