/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.PhongBanBUS;
import DTO.PhongBanDTO;
import java.awt.Graphics;
import java.awt.event.MouseAdapter;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chicu
 */
public class FrmPhongBan extends javax.swing.JPanel {

    PhongBanBUS phongBanBus;
    PhongBanDTO phongBanDTO;
    DefaultTableModel defaultTableModel;

    /**
     * Creates new form FrmPhongBan
     */
    public FrmPhongBan() {
        initComponents();
        phongBanBus = new PhongBanBUS();
        phongBanDTO = new PhongBanDTO();
        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        departmentTable.setModel(defaultTableModel);
        defaultTableModel.addColumn("Mã phòng ban");
        defaultTableModel.addColumn("Tên phòng ban");
        defaultTableModel.addColumn("Số điện thoại");
        setPBData(phongBanBus.getPhongBan());
    }

    public void setPBData(ArrayList<PhongBanDTO> departments) {
        for (PhongBanDTO department : departments) {
            defaultTableModel.addRow(new Object[]{
                department.getMaPB(),
                department.getTenPB(),
                department.getSoDienThoai()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel(){    
            public void paintComponent(Graphics g){     
                ImageIcon icon=new ImageIcon(getClass().getResource("/GUI/Images/bg2.png"));     
                g.drawImage(icon.getImage(),0 , 0, jPanel2.getWidth(), jPanel2.getHeight(), null);       
                setOpaque(false);     
                super.paintComponent(g);     
            } 
        };
        departmentIDLabel = new javax.swing.JLabel();
        departmentIDField = new javax.swing.JTextField();
        departmentPhoneNumLabel = new javax.swing.JLabel();
        departmentNameField = new javax.swing.JTextField();
        departmentDeleteBtn = new javax.swing.JButton();
        departmentSaveBtn = new javax.swing.JButton();
        departmentCancelBtn = new javax.swing.JButton();
        departmentAddBtn = new javax.swing.JButton();
        departmentPhoneNumField = new javax.swing.JTextField();
        departmentNameLabel = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        departmentTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel(){    
            public void paintComponent(Graphics g){     
                ImageIcon icon=new ImageIcon(getClass().getResource("/GUI/Images/bg2.png"));     
                g.drawImage(icon.getImage(),0 , 0, jPanel1.getWidth(), jPanel1.getHeight(), null);       
                setOpaque(false);     
                super.paintComponent(g);     
            } 
        };
        jLabel1 = new javax.swing.JLabel();
        selectBtn = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 600));

        departmentIDLabel.setText("Mã phòng ban:");

        departmentPhoneNumLabel.setText("Số điện thoại: ");

        departmentDeleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/xoa.png"))); // NOI18N
        departmentDeleteBtn.setText("Xóa");
        departmentDeleteBtn.setPreferredSize(new java.awt.Dimension(90, 30));
        departmentDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentDeleteBtnActionPerformed(evt);
            }
        });

        departmentSaveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/sua.png"))); // NOI18N
        departmentSaveBtn.setText("Sửa");
        departmentSaveBtn.setEnabled(false);
        departmentSaveBtn.setPreferredSize(new java.awt.Dimension(90, 30));
        departmentSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentSaveBtnActionPerformed(evt);
            }
        });

        departmentCancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/huy.png"))); // NOI18N
        departmentCancelBtn.setText("Hủy");
        departmentCancelBtn.setPreferredSize(new java.awt.Dimension(90, 30));
        departmentCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentCancelBtnActionPerformed(evt);
            }
        });

        departmentAddBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/add.png"))); // NOI18N
        departmentAddBtn.setText("Thêm");
        departmentAddBtn.setPreferredSize(new java.awt.Dimension(90, 30));
        departmentAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentAddBtnActionPerformed(evt);
            }
        });

        departmentNameLabel.setText("Tên phòng ban:");

        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/search.png"))); // NOI18N
        searchBtn.setText("Tìm kiếm");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(departmentNameLabel)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(departmentAddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(departmentSaveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(departmentDeleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(departmentCancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(departmentIDLabel)
                    .addComponent(departmentIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departmentPhoneNumLabel)
                    .addComponent(departmentPhoneNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departmentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchBtn)
                .addGap(68, 68, 68))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(departmentIDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(departmentIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(departmentNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(departmentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(departmentPhoneNumLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(departmentPhoneNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departmentAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departmentDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departmentCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departmentSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchBtn)
                .addContainerGap())
        );

        departmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        departmentTable.setOpaque(false);
        departmentTable.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(departmentTable);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        jPanel1.setPreferredSize(new java.awt.Dimension(207, 24));

        jLabel1.setText("Thông tin phòng ban");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        selectBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/chon.png"))); // NOI18N
        selectBtn.setText("Chọn");
        selectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void departmentCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentCancelBtnActionPerformed
        // TODO add your handling code here:
        departmentIDField.setText("");
        departmentIDField.setEnabled(true);
        departmentNameField.setText("");
        departmentPhoneNumField.setText("");
        departmentSaveBtn.setEnabled(false);
    }//GEN-LAST:event_departmentCancelBtnActionPerformed

    private void departmentAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentAddBtnActionPerformed
        // TODO add your handling code here:
        if ("".equals(departmentIDField.getText()) || "".equals(departmentNameField.getText())) {
            JOptionPane.showMessageDialog(this, "Không được bỏ trống dữ liệu nhập vào !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            phongBanDTO.setMaPB(departmentIDField.getText());
            phongBanDTO.setTenPB(departmentNameField.getText());
            phongBanDTO.setSoDienThoai(departmentPhoneNumField.getText());
            phongBanBus.addPhongBan(phongBanDTO);
            JOptionPane.showMessageDialog(this, "Thêm phòng ban thành công !!!");
            defaultTableModel.setRowCount(0);
            setPBData(phongBanBus.getPhongBan());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);

        }
    }//GEN-LAST:event_departmentAddBtnActionPerformed

    public FrmMain frmMain;

    public void showSearchField(JButton btn) {
        JDialog dialog = new JDialog(frmMain, "Tìm kiếm", true);
        dialog.setSize(908, 594);
        dialog.setLocationRelativeTo(null);
        dialog.add(new FrmTimPhongBan(btn, dialog));
        dialog.setVisible(true);
    }

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        showSearchField(searchBtn);

    }//GEN-LAST:event_searchBtnActionPerformed

    private void selectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBtnActionPerformed
        // TODO add your handling code here:
        showInfo();
        departmentSaveBtn.setEnabled(true);
    }//GEN-LAST:event_selectBtnActionPerformed

    private void departmentDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentDeleteBtnActionPerformed
        // TODO add your handling code here:
        int row = departmentTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn phòng ban cần xóa !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa không ?");

            if (confirm == JOptionPane.YES_OPTION) {
                String departmentTableCode = String.valueOf(departmentTable.getValueAt(row, 0));

                phongBanBus.deletePhongBan(departmentTableCode);
                defaultTableModel.setRowCount(0);
                setPBData(phongBanBus.getPhongBan());
            }
        }
    }//GEN-LAST:event_departmentDeleteBtnActionPerformed

    private void departmentSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentSaveBtnActionPerformed
        // TODO add your handling code here:
        int row = departmentTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn phòng ban cần sửa !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            phongBanDTO.setMaPB(departmentIDField.getText());
            phongBanDTO.setTenPB(departmentNameField.getText());
            phongBanDTO.setSoDienThoai(departmentPhoneNumField.getText());
            
            phongBanBus.updatePhongBan(phongBanDTO);
            JOptionPane.showMessageDialog(this, "Sửa phòng ban thành công !!!");
            defaultTableModel.setRowCount(0);
            setPBData(phongBanBus.getPhongBan());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_departmentSaveBtnActionPerformed

    public void showInfo() {
        int row = departmentTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn phòng ban cần sửa !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            String departmentCode = String.valueOf(departmentTable.getValueAt(row, 0));
            phongBanDTO = phongBanBus.findPBByID(departmentCode);
            departmentIDField.setText(phongBanDTO.getMaPB());
            departmentIDField.setEnabled(false);
            departmentNameField.setText(phongBanDTO.getTenPB());
            departmentPhoneNumField.setText(phongBanDTO.getSoDienThoai());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton departmentAddBtn;
    private javax.swing.JButton departmentCancelBtn;
    private javax.swing.JButton departmentDeleteBtn;
    private javax.swing.JTextField departmentIDField;
    private javax.swing.JLabel departmentIDLabel;
    private javax.swing.JTextField departmentNameField;
    private javax.swing.JLabel departmentNameLabel;
    private javax.swing.JTextField departmentPhoneNumField;
    private javax.swing.JLabel departmentPhoneNumLabel;
    private javax.swing.JButton departmentSaveBtn;
    private javax.swing.JTable departmentTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton selectBtn;
    // End of variables declaration//GEN-END:variables
}
