/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author chicu
 */
public class FrmTTPM extends javax.swing.JPanel {

    /**
     * Creates new form FrmTTPM
     */
    public FrmTTPM() {
        initComponents();
        jLabel2.setText("<html> - Phần mềm sẽ giúp việc quản lý nhân sự trong công ty "
                + "được dễ dàng và hiệu quả, nhất là ở các công ty lớn, số nhân sự đông,"
                + "từ việc tiếp nhận nhân sự (quản lý hồ sơ nhân sự) cho đến quản lý lương bổng.<br><br>"
                + "- Phần mềm đầy đủ các chức năng cho việc quản lý nhân sự như:<br>"
                + "+ Quản lí nhân viên.<br>"
                + "+ Quản lí chức vụ.<br>"
                + "+ Quản lí phòng ban.<br>"
                + "+ Quản lí lương bổng.<br>"
                + "+ Nhập/Xuất danh sách nhân viên, lương bổng.</html>"
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("PHẦN MỀM QUẢN LÝ NHÂN SỰ");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(240, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
